name: Check Pull Request

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Inatall Dependencies
      - run: yarn install

      - name: Test
      - run: yarn ts-check
      - run: yarn lint:all
      - run: yarn test

      - name: Build
      - run: yarn build

      - name: Check Size
      - run: yarn size-limit
